name: My first github actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
  Print-name: runs-on: ubuntu-latest
    steps:
      - run: echo "hello new world!! I'm Vishal :)"
