name: github actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Install node_modules
        run: npm i
      - name: build the project
        run: npm run build
      - name: Setup Finish
        run: echo "Successfully Setup First Project."
      - run: tree
  print-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello i'm Vishal."
